### ISSUE TITLE
Crosshair loses track of a counterexample when `== `is replaced by `in`

### ISSUE THREAD

**Issue by poneill** [pschanely/CrossHair#112]
**Is your feature request related to a problem? Please describe.**
Consider the following gist: https://gist.github.com/b3a5ffed6cd2ec5b30d5b7011f697c42

It contains two implementations of a function to determine whether a string contains balanced parentheses.  The functions have a deliberately incorrect postcondition, namely that they should always return `True`.  In the first function, `is_balanced1`, crosshair correctly deduces that this postcondition is false when `input_str` is not balanced.  However in `is_balanced2`, which only differs from `is_balanced1` in one line for checking if a character is a left paren, crosshair cannot tell that the postcondition is false.  That is:

`if c == '('`

sucessfully triggers a counterexample, but

`if c in 'c'`

does not.

**Describe the solution you'd like**
Ideally crosshair would be able to detect that the postcondition in `is_balanced2` is incorrect, just as in `is_balanced1`.  Failing that, it might be helpful to elaborate the section of the docs that discusses crosshair's limitations in order to make clearer what crosshair should and shouldn't be expected to handle, so that users can understand what is a bug, and what's simply beyond the state of the art.

**Describe alternatives you've considered**
N/A.

Thanks!

**Comment by pschanely** [comment]
These reports really help; thank you for the complete example too!

I can reproduce the issue. Should be able to get a fix in in a day or two. More later!

**Comment by poneill** [comment]
Sure thing, thanks for taking a look at it.

**Comment by pschanely** [comment]
A small update: this will take a little longer than I thought - the Python interpreter circumvents a str.__contains__ function call in this example (for performance reasons), which means the usual way CrossHair hooks into the interpreter doesn't work.

I have another way of dealing with this kind of problem though - more later!

**Comment by pschanely** [comment]
Fixed in 0.0.15! ([your example](https://crosshair-web.org/?gist=b3a5ffed6cd2ec5b30d5b7011f697c42))
