### ISSUE TITLE
Use more flake8 

### ISSUE THREAD

**Issue by pschanely** [pschanely/CrossHair#119]
Right now (in [precommit.py](https://github.com/pschanely/CrossHair/blob/98bc53798467f03c71ad63f041c7177894c86aa8/precommit.py#L95)) we only enable a few checks (E9, F63, F7, F82).

Looks like there are a lot of other useful ones in there; investigate moving to a set of blocklisted checks.

**Comment by nicpayne713** [comment]
Hello, I briefly looked over your repo and I'm unfamiliar with using a .py file for precommit... is there any reason you don't configure pre-commit with a `.pre-commit-config.yaml` and then run `pre-commit run all` or have a hook that runs pre-commit for you? A custom .py file feels like a lot of unnecessary customization at first glance... I'm not an expert here by the way, so if there's good reason I'm more than happy to be wrong. If though you'd like to transition to a pre-commit config I'd be more than happy to help close this issue with one. 
Cheers.

**Comment by nicpayne713** [comment]
Hey @pschanely as we are discussing pre-commit elsewhere, what did you have in mind for extending your current .py file? I'd be happy to help move that along and make it more usable regardless of your decision to migrate to pre-commit or not

**Comment by nicpayne713** [comment]
Cool I'll work on some small edits on a branch for this issue - will include `isort` by the way
