### ISSUE TITLE
Add a SymbolicInt.bit_count() implementation

### ISSUE THREAD

**Issue by pschanely** [pschanely/CrossHair#124]

**Comment by pschanely** [comment]
In Python 3.10, you can call bit_count() on an integer, and it'll tell you how many 1s are in the binary form of that integer.

CrossHair doesn't implement bit_count(), so complains that SymbolicInt does not have the method in [this example](https://crosshair-web.org/?crosshair=0.1&python=3.8&gist=fd53fad5906503321b6dbb59b043ff31).

We should implement bit_count on [SymbolicInt](https://github.com/pschanely/CrossHair/blob/850667b8646ddd5b30d5411f6c1777d7e4252831/crosshair/libimpl/builtinslib.py#L896).  (note it sounds similar to `bit_length()`, but is different)

We probably don't need to bring the SMT solver into this one - I'd just implement it recursively; check if it equals 0 or 1 and return the appropriate things, otherwise check the lowest bit and call it again on the input shifted right one bit.

To test, I'd add a new method to [builtinslib_ch_test.py](https://github.com/pschanely/CrossHair/blob/master/crosshair/libimpl/builtinslib_ch_test.py).

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by aadityasinha-dotcom** [comment]
> > Can I work on this issue?
> 
> Of course, it's yours! Feel free to ask more questions here or on the gitter chat, and thank you!

Can you explain me about this issue?

**Comment by aadityasinha-dotcom** [comment]
> > Can you explain me about this issue?
> 
> Yup. So first maybe make sure you understand what bit_count() does - not everyone has a lot of experience with bitwise logic and algorithms. Then maybe review my comment above and let me know what does and doesn't make sense.
> 
> But to try and summarize as much as possible: we want to re-implement bit_count() in regular Python, as a new method on SymbolicInt. Maybe start there, and I could help you with testing after you have something maybe?

Ok, so we have to implement a bit_count() function as a new method.

**Comment by pschanely** [comment]
> Ok, so we have to implement a bit_count() function as a new method.

That's right. Happy to help you along if you want to give it a try.
