### ISSUE TITLE
CrossHair is generating SmtList rather than List type for Union type

### ISSUE THREAD

**Issue by charles-l** [pschanely/CrossHair#15]
**Expected vs actual behavior**
When I run the below code, with `crosshair check t.py`, it raises the assertion (i.e. passes in a `SmtList` rather than a `List`), even though the mypy type states that `x` should be a `List` or `Dict`:

```
t.py:11:error:AssertionError: Shouldn't have gotten type: <class 'crosshair.core.SmtList'> when calling f(self = 1, x = [0, 0, 0])
```

**To Reproduce**

```python
from typing import List, Union, Dict
def f(self, x: Union[List, Dict]):
    '''
    post: True
    '''
    if isinstance(x, list): # using isinstance is convention for mypy to know the type of x in the branch
        pass
    if isinstance(x, dict):
        pass
    else:
        assert False, f"Shouldn't have gotten type: {type(x)}"
```

EDIT: Updated code with a Union, since I'm assuming `SmtList` is the proxy type.

If the type passed in is going to be different, what's the best way of working with Union types so that both CrossHair and MyPy understand the code?

**Comment by pschanely** [comment]
Thank you for the bug report! These are really valuable and I hope you can keep them coming!

Although CrossHair cannot maintain a complete type illusion, I'd like the case you describe here to be supported. In fact, CrossHair should also support the non-union case as well. (with just List and Dict). We can achieve this illusion with some monkey-patching on isinstance() and issubclass().

I have just committed some fixes that do this. Let me know if it works for you? (I think you can just pip uninstall + reinstall). Finally, I am not confident that I've covered all the cases, so please let me know if you run into similar issues in the future!

**Comment by charles-l** [comment]
Wow -- thanks for the quick fix! Sorry for the slow response on my end. 

It looks like that fixed the issue I was seeing with isinstance. Thanks!

**Comment by pschanely** [comment]
No worries, and great!

In unrelated news, as of minutes ago, I've released https://crosshair-web.org/ - it could be handy for communicating test cases for reproduction!
