### ISSUE TITLE
memoryview raises TypeError

### ISSUE THREAD

**Issue by kionactf** [pschanely/CrossHair#153]
**Expected vs actual behavior**
expected: (No error)
actual behavior: error: TypeError: memoryview: a bytes-like object is required, not 'SymbolicBytes' when calling make_bytes(key = b'\x00')

**To Reproduce**
def make_bytes(key:bytes ) -> None:
    """
    pre: len(key) > 0
    """
    memoryview(key)

I know that Crosshair deal with "isinstance(key, bytes)" well, so I expect that memoryview is dealt with too.

**Comment by pschanely** [comment]
Indeed, memoryview should be supported but isn't. Thank you for the report!!

Looks like there's a fair amount of functionality to implement, but hoping that I can have something done this weekend. Stay tuned!

**Comment by pschanely** [comment]
Quick update: this will take a little longer than I'd hoped; it's fairly easy to avoid the TypeError by realizing the symbolic bytes/bytearray, but we really want to preserve symbolics after creating the memoryview. Since memoryview is implemented in C, I need to write a parallel version of it in Python, and the implementation details aren't quite trivial. That said, I think I should be able to get it done in another week or two. More soon.

**Comment by pschanely** [comment]
I'll released something for this in v0.0.21! CrossHair should be able to reason about memoryviews, so long as we're talking about single-dimensional byte data. If you're using other datatypes or multidimensional data, e.g. from [memoryview.cast](https://docs.python.org/3/library/stdtypes.html#memoryview.cast), CrossHair won't be able to find counterexamples effectively (but hopefully doesn't crash!).

That said, I don't have **any** realistic examples of memoryviews in practice, so I'd love it if you can let me know how it works for you (does it uncover another bug? does it reason about your logic effectively?).

**Comment by kionactf** [comment]
Thank you for adding the feature that handles memoryview.

Because I wanted to apply crosshair to AES library, I created this issue.
There is no bug in the following code, but it uses memoryview for checking input data is byte-like string.

```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

def aes(key:bytes, msg:bytes):
    """
    pre: len(key)==16 and len(msg)==16
    post: len(__return__) == 16
    """
    # internally, it calls memoryview for checking key is byte-like string.
    cipher = Cipher(algorithms.AES(key), modes.ECB(), default_backend())
    encryptor = cipher.encryptor()
    c = encryptor.update(msg) + encryptor.finalize()
    return c
```

I do not know this example is realistic, but some applications would use memoryview instead of isinstance(key, bytes).
implementing memoryview issue saves time for us to find bugs for libraries that includes memoryview code.

**Comment by pschanely** [comment]
Got it, and thanks for the example! Hopefully, CrossHair doesn't raise an exception on this example anymore.

That said, CrossHair won't likely find anything useful with logic in extension modules like in this cryptography package - those modules are implemented in C, and CrossHair only understands logic at the Python level. Still, it's nice to document your expectations!
