### ISSUE TITLE
Readthedocs is missing changelogs for 0.0.24 and 0.0.25

### ISSUE THREAD

**Issue by Zac-HD** [pschanely/CrossHair#170]
Eg https://github.com/pschanely/CrossHair/releases/tag/v0.0.25 exists, but https://crosshair.readthedocs.io/en/latest/changelog.html is missing the last two versions. 

They *do* appear in https://github.com/pschanely/CrossHair/blob/main/doc/source/changelog.rst so probably this is a build issue somewhere?

**Comment by pschanely** [comment]
[Fixed](https://crosshair.readthedocs.io/en/latest/changelog.html#version-0-0-25)! Thanks again!

**Comment by Zac-HD** [comment]
Happy to help!
