### ISSUE TITLE
Unable to build/install latest release of CrossHair-0.0.32 on Windows

### ISSUE THREAD

**Issue by azewiusz** [pschanely/CrossHair#179]
**Expected vs actual behavior**
No errors in console when running "pip install ." , there is no issue like below for CrossHair-0.0.31 release
pip 22.3 from Anaconda (python 3.7)
What error do I get in PowerShell on Windows 10:
```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\azewi\Downloads\CrossHair-0.0.32\CrossHair-0.0.32\setup.py", line 31, in <module>
          long_description=open("README.md")
        File "C:\Users\azewi\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2704: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**To Reproduce**
If appropriate, enter your test case into [crosshair-web.org](https://crosshair-web.org/), create a gist, and link to it here!
Please try to minimize the size/complexity of your test case. Thanks!

**Comment by pschanely** [comment]
Ah, thank you for this report! I've falling exactly into [the trap described here](https://peps.python.org/pep-0597/#using-the-default-encoding-is-a-common-mistake), where the default encoding to `open()` is platform-specific.

Confusingly, my windows 3.7 python build (pyenv, rather than anaconda) seems to have utf-8 as the default.
Anyway! This is an easy fix - I'll push something momentarily.

**Comment by pschanely** [comment]
BTW: I finally cut a release including this v0.0.33. Thanks again for the report and I hope to hear from you again sometime!

**Comment by azewiusz** [comment]
Thanks for creating and maintaining  this tool !
Kind regards,
Tomasz

pt., 11 lis 2022 o 18:35 Phillip Schanely ***@***.***>
napisał(a):
