### ISSUE TITLE
Any class with an attribute called "typ" returns an error upon creation

### ISSUE THREAD

**Issue by petrusboniatus** [pschanely/CrossHair#191]
**Expected vs actual behavior**
No error or better error message.

**To Reproduce**
https://gist.github.com/pschanely/d2d083a5b9e07847a5e26b65ee77d795

**Comment by pschanely** [comment]
Oh, this is pretty funny. Thank you for the repro case, and I can't wait to find out what else you might run into in your experiments.

I've got a fix in 480c5ac1efff9368d65d9af43db129b8a0f523d2 and I'll be cutting a release this week. Will close this out then. Thanks again!

**Comment by pschanely** [comment]
Shipped in [v0.0.35](https://crosshair.readthedocs.io/en/latest/changelog.html#version-0-0-35)!
