### ISSUE TITLE
Some easy cases cannot be solved

### ISSUE THREAD

**Issue by usepr** [pschanely/CrossHair#207]
```
def f(param: str) -> str:
    '''
    pre: "sx250" in param
    post: "sx250" not in __return__
    '''
    z = 'x'*40 + param + 'y'
    return z
```

```
def g(param: str, a:bool, b:bool) -> str:
    '''
    pre: "sx250" in param
    post: "sx250" not in __return__
    '''
    if b and not a:
        z = "" + param + "y"
    else:
        z = ""
    return z
```

Run using `crosshair check filename.py`, no counterexamples are found.

**Comment by usepr** [comment]
I added the `--per_condition_timeout=` parameter. It works

**Comment by usepr** [comment]
@pschanely 

Another case:
```
def f(param: str) -> str:
    '''
    pre: "sx250" in param
    post: "sx250" not in __return__
    '''
    t = 3
    if t > 1:
        z = "abc"
    else:
        z = 'x'*40 + param + 'y'
    return z
```
Even `--per_condition_timeout=100` is added, no counterexample is found.

**Comment by pschanely** [comment]
> Even `--per_condition_timeout=100` is added, no counterexample is found.

In this case, `t` > 1, so "abc" is always returned and the postcondition is always true. (FWIW, I do feel like crosshair should have better ways to explain what it's doing or what it has or hasn't figured out or ... something, but not exactly sure how that would work)

Anyway, I have a small patch for improved string containment checks [here](https://github.com/pschanely/CrossHair/pull/208); I'll cut a release this week and ping this thread again then. Keep those examples coming!

**Comment by usepr** [comment]
> > Even `--per_condition_timeout=100` is added, no counterexample is found.
> 
> In this case, `t` > 1, so "abc" is always returned and the postcondition is always true. (FWIW, I do feel like crosshair should have better ways to explain what it's doing or what it has or hasn't figured out or ... something, but not exactly sure how that would work)
> 
> Anyway, I have a small patch for improved string containment checks [here](https://github.com/pschanely/CrossHair/pull/208); I'll cut a release this week and ping this thread again then. Keep those examples coming!

I pasted the wrong code. It should be `t>100`.

**Comment by pschanely** [comment]
> I pasted the wrong code. It should be `t>100`.

Gotcha - that makes sense.

[Version 0.0.39](https://pypi.org/project/crosshair-tool/0.0.39/) should be much faster with problems like this: please re-open this issue if not!

We may hit other bottlenecks as you try to scale this up to realistic examples - I hope you'll continue to share example code that isn't analyzed effectively. Thank you!
