### ISSUE TITLE
Add support for NewType

### ISSUE THREAD

**Issue by brydenfogelman** [pschanely/CrossHair#259]
Using `typing.NewType` leads to the following error:

```
TypeError: bleh.math.Number is not a module, class, method, or function.
```

Example to reproduce:
```python
from typing import NewType

Number = NewType("Number", int)


def add(a: Number, b: Number) -> Number:
    """
    post: __return__ >= 0
    """
    return Number(a + b)


if __name__ == "__main__":
    print(Number(-1) >= 0)
```

Is there a reason this behavior isn't supported? Is there a workaround?

**Comment by pschanely** [comment]
Thanks for the report!
There's no reason not to support that - it's just an oversight. I've fixed it in [v.0.0.54](https://pypi.org/project/crosshair-tool/0.0.54/). I'd love it if you can try it out again and let me know how it goes.

**Comment by brydenfogelman** [comment]
This works -- thanks! I appreciate the incredibly speedy fix!

**Comment by pschanely** [comment]
Great. Thank you for letting me know about the issue in the first place! I hope to hear from you again about what works well for you and what doesn't!
