### ISSUE TITLE
(option to) Treat leading assertions as preconditions

### ISSUE THREAD

**Issue by Zac-HD** [pschanely/CrossHair#27]
Minimising `crosshair`-specific configuration maximises ease of experimentation and adoption.  To that end, I'd like to propose that *leading* assertions in a function could be treated as preconditions rather than invariants.  An example:

```python
def fib(n: int) -> int:
    assert n >= 1       # treated like `pre: n >= 1`
    ...                 # calculate the result here
    assert result >= 1  # Checked as usual
    return result
```

Such leading assertions currently *must* hold - because no work is done before they are checked, they are logically equivalent to preconditions.  Treating them as such would allow preconditions to be checked at runtime without duplicating them, and synergises well with #22 to support precise checks without any `crosshair`-specific configuration.

**Comment by Zac-HD** [comment]
An alternative would be to special-case a function called `assume`, which might be implemented as

```python
def assume(predicate):
    assert predicate
```

and treat `assume(x)` as expressing a precondition of `bool(x) is True` rather than an assertion.  This would also play nicely with [the `hypothesis.assume()` function](https://hypothesis.readthedocs.io/en/latest/details.html#making-assumptions), which does exactly this (albeit implemented with a special exception type).  Other projects could add domain-specific logic such as logging that the precondition was violated or attempting to recover to a known-good state.

**Comment by pschanely** [comment]
I am warming up to this request generally. And, FWIW, I think some sort of hypothesis cooperation also makes a lot of sense.

In the assert version, do you imagine pulling the AST, and making the assumption that the first non-assert statement in the body signals the transition from preconditions to postconditions?

**Comment by Zac-HD** [comment]
> In the assert version, do you imagine pulling the AST, and making the assumption that the first non-assert statement in the body signals the transition from preconditions to postconditions?

Exactly, though it should probably be configurable at the project level and also have some local way to force all-assertions-are-invariants.

**Comment by pschanely** [comment]
@Zac-HD  This is in-progress :)

In other modes, CrossHair detects other kinds of exceptions too. I'm thinking this is useful under "assert mode" as well.

One notable exception might be ValueError & TypeError which are likely validating inputs? Or perhaps any exception raised directly in the body of the function under analysis? WDYT?

**Comment by Zac-HD** [comment]
> One notable exception might be ValueError & TypeError which are likely validating inputs? Or perhaps any exception raised directly in the body of the function under analysis? WDYT?

Maybe as a separate flag - I think this is probably useful, but *also* prone to concealing real bugs in a way that assertions-only is not.

**Comment by pschanely** [comment]
A basic version of this is in HEAD! ([minimalistic docs](https://github.com/pschanely/CrossHair/blob/master/doc/analysis_kind_asserts.md))

At least one leading assert is required, and it'll complain about any kind of exception.

There are no flags/options to control the behavior yet; I think I'm inclined to wait for feedback from real use cases? Another option for exception handling would be to borrow just the [`raises: <exception type>`](https://github.com/pschanely/CrossHair/blob/master/doc/analysis_kind_pep316.md#how-to-write-contracts) pattern from the docstring parser for suppressing exception reports.

**Comment by pschanely** [comment]
Docstring directives like "raises: IndexError" should work.
Complete docs for assert mode [are here now](https://crosshair.readthedocs.io/en/latest/kinds_of_contracts.html#analysis-kind-asserts).
Closing this FR!
