### ISSUE TITLE
`TypeError` in bytes regex

### ISSUE THREAD

**Issue by Zac-HD** [pschanely/CrossHair#276]
```python
import re

def binary_regex(buf: bytes) -> None:
  '''
  post: True
  '''
  re.search(b"ab+c", b".....")
```
raises `/tmp/main.py:7: error: TypeError:  when calling binary_regex(b'')`

**Comment by pschanely** [comment]
Fixed in [v0.0.64](https://pypi.org/project/crosshair-tool/0.0.64/)!
