### ISSUE TITLE
Support named `dict` init syntax

### ISSUE THREAD

**Issue by tybug** [pschanely/CrossHair#279]
https://crosshair-web.org/?crosshair=0.1&python=3.8&gist=22fa25f6f4b01b10328fa9dc99c83fb7, from https://github.com/HypothesisWorks/hypothesis/pull/4034

**Comment by pschanely** [comment]
Oh geez, how have I not hit this yet? Thank you!

**Comment by pschanely** [comment]
Fixed in v0.0.63!
