### ISSUE TITLE
crosshair watch raises AttributeError: 'Namespace' object has no attribute 'report_all'

### ISSUE THREAD

**Issue by lhayhurst** [pschanely/CrossHair#29]
**Expected vs actual behavior**
Running `crosshair watch`  with Python file or directory raises exception.

```
Traceback (most recent call last):
  File "envs/default/bin/crosshair", line 8, in <module>
    sys.exit(main())
  File "/home/lhayhurst/aq/code/testing/envs/default/lib/python3.7/site-packages/crosshair/main.py", line 475, in main
    options = process_level_options(args)
  File "/home/lhayhurst/aq/code/testing/envs/default/lib/python3.7/site-packages/crosshair/main.py", line 60, in process_level_options
    arg_val = getattr(command_line_args, optname)
AttributeError: 'Namespace' object has no attribute 'report_all'
```

**To Reproduce**
1. Install crosshair via pip 

```
$ envs/default/bin/pip freeze | grep -i crosshair
crosshair-tool==0.0.3
```

2. Touch an empty python file
```
touch foo.py
```
3. Run crosshair watch on that file
```
envs/default/bin/crosshair  watch foo.py
```

The above exception stack should be generated.

Looking through the source code, it looks like the `report_all` flag should only be processed when run with `crosshair check`, so it seems the wires are getting crossed.

**Comment by pschanely** [comment]
Thank you for the detailed report and diagnostics!
I think this is already fixed, but haven't made a release recently. I just cut 0.0.4; so would you give that a try and let me know how it goes?

This is the first release with a customized z3 build, so there is also a chance that something else won't work - do me a favor and make sure to yell if that's the case?

Thanks again!

**Comment by lhayhurst** [comment]
great success!

![image](https://user-images.githubusercontent.com/216183/79082567-e4692700-7cdb-11ea-93b8-f4a303290549.png)

ty
