### ISSUE TITLE
Implement a symbolic collections.deque

### ISSUE THREAD

**Issue by pschanely** [pschanely/CrossHair#3]
Per #2, deque cannot be analyzed symbolically. Tentative plan is to implement a "dumb" version on top of a generic list: https://github.com/pschanely/CrossHair/blob/56ce14ee44c1103121c483f479d3d1a5a4bd3438/crosshair/simplestructs.py#L57

**Comment by oneEdoubleD** [comment]
I'll take a look at this once you've finished refactoring the implementation pattern

**Comment by pschanely** [comment]
Thank you for taking a look! I've given the basic framework for how I imagined it here:

https://github.com/pschanely/CrossHair/commit/7a4e4606fdbbb6c34825ae79e5c25af4ca5ff528

But use your best judgement too, and feel free to be noisy in the chat while you investigate!

**Comment by pschanely** [comment]
Just a note for later: pypy actually also has a pure python implementation of this: https://bitbucket.org/pypy/pypy/src/default/lib_pypy/_collections.py

**Comment by amacfie** [comment]
> Just a note for later: pypy actually also has a pure python implementation of this: https://bitbucket.org/pypy/pypy/src/default/lib_pypy/_collections.py

@pschanely If we run CrossHair with pypy does that remove the need for symbolic versions of stuff pypy implements in pure python like `collections.deque`? Are there other benefits of running CrossHair with pypy?
