### ISSUE TITLE
mypy typechecking and circular dependency issues

### ISSUE THREAD

**Issue by CoenSchalkwijk** [pschanely/CrossHair#32]
**Expected vs actual behavior**
I'm not _fully_ sure if it is sensible to expect that this will work. But here goes: In my code I have circular dependencies. I'm not in a position to remove them. I also have mypy type checking in place. MyPy can handle circular dependencies but in order for the code to function, the 'offending' imports are put behind a 'if TYPE_CHECKING:' check. Doing so, MyPy can still perform it's magic.

When I try to have crosshair look at this code, it cannot resolve the imports behind the TYPE_CHECKING flag.

**To Reproduce**

In a module 'foobar', have an ```__init__.py``` and:

Bar.py:
```
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from foobar.foo import Foo


class Bar():

    def __init__(self, foo: "Foo") -> None:
        pass
```
Foo.py:
```
from foobar.hidey import Hidey


class Foo():
    pass
```
Hidey.py
```
from foobar.bar import Bar 


class Hidey():
    pass
```

Running crosshair ('python3 ../CrossHair/crosshair/main.py watch ./foobar') will result in something like:
```
NameError: name 'Foo' is not defined
```

Removing the TYPE_CHECKING flag, results in:
```
cannot import name 'Foo' from partially initialized module 'foobar.foo' (most likely due to a circular import) 
```

**Comment by pschanely** [comment]
First, thank you for the very detailed repro instructions!

This is a tricky problem and solving it would unlock a lot of use cases for CrossHair. Unfortunately, it is also one that I'm going to need to think about. First, I'll start with some internals:

Unlike mypy, CrossHair works by actually importing and running your code. It just passes very special fake values to your functions to do its magic. It needs to understand both the function under test, as well as the types on the supplied parameters. In your example, for instance, if we remove the `TYPE_CHECKING` guard, simply running `python foobar/bar.py` (without CrossHair) will produce the same error.

That said, perhaps we can do some trickery. I'm imagining something like: import with `TYPE_CHECKING` off and then re-import with it on. I'll experiment with this over the next few days and report back with what I discover.

**Comment by CoenSchalkwijk** [comment]
I understand. I do consider circular dependencies as unwanted design, to be avoided as much as possible. Unfortunately I'm working with a code base that does have 'm, in large amounts, and no time to remove/replace them. 
What I _can_ do and might help find a way around it, is the _way_ I do these imports:

I'm also not very fond of using the TYPE_CHECKING flag; very framework specific, limits my control over the code. So I'd rather do without it. Maybe the trickery can cover something like replacing the import statement with a function that does conditional imports:

```
from no.circular.dependency.module.a_class import A_class
 
cond_import({"module_name":"class(es)"})

class ThisClass:
    ...
```
Then in the cond_import function, I have a single TYPE_CHECKING flag and all I need to do the importing and maybe break/prevent circular importing and what not?

**Comment by pschanely** [comment]
Yeah, I suspect that hiding the TYPE_CHECKING guard will confuse type checkers.

However, I just attempted an odd sort of fix where CrossHair will detect the presence of these guards and attempt a re-import with them turned on. Not all modules are guaranteed to re-import properly, but this behavior still seems like a good compromise to me.

@CoenSchalkwijk Would you try again at HEAD and let me know how it goes? Thanks for your help here!
