### ISSUE TITLE
python's `sum` function causes internal issues, with the wrong type-hint

### ISSUE THREAD

**Issue by Abhiram98** [pschanely/CrossHair#322]
I'm trying to use crosshair's `diffbehavior` analysis, to find the equivalence (or lack thereof) of these two functions:

```python
def original(int_list: list[int]):
    count = 0
    for i in int_list:
       count +=i
    return count
```

```python
def rewrite(int_list: list[int]):
    count = 0
    for sublist in int_list:
        count += sum(sublist)
    return count
 ```

Crosshair fails to find a conterexample, even though something simple like `int_list=[123]` would work. It seems like crosshair throws an internal error, which stops it from proceeding with its analysis. Here's a jist of the internal error
```
__exit__() Proxy intolerace: 'SymbolicInt' object is not iterable at Traceback (most recent call last):
  File "crosshair/diff_behavior.py", line 72, in describe_behavior
    ret = fn(*args.args, **args.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "temp/test.py", line 5, in original
    for i in int_list:
             ^^^^^^^^
  File "crosshair/objectproxy.py", line 332, in __iter__
    return iter(self._wrapped())
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'SymbolicInt' object is not iterable
```

PS: Thank you for the awesome tool!

**Comment by pschanely** [comment]
First, please accept my apologies for the delays in responding! Just now returning from an extended holiday.

There are several levels of things to do here, and I'm sorry to say that it's unlikely that I'll be able to prioritize all of them. In severity order:
1. Prevent the tool from failing in this case. (but do not find the counterexample)
2. Surface a counterexample, but with this odd internal message about "SymbolicInt" and crosshair-related stack frames.
3. Surface a counterexample with the proper exception message ('int' object is not iterable) but still including crosshair-related stack frames.
4. Surface a counterexample with the exception message and stack frames that you would see exactly when running it.

I should mention here that CrossHair is meant to act as a compliment to a type checker like mypy, and I generally don't prioritize capabilities that would be subsumed by type checkers. (CrossHair is such a complex system that we need to take simplifying assumptions wherever we can find them)

But let me initially try to address 1 & 2. Expect another update in a day or two. Thank you for the report!

**Comment by Abhiram98** [comment]
I am also happy to help contribute a fix here. 

From my understanding of the code, the function `suspected_proxy_intolerance_exception` in file [core.py:173](https://github.com/pschanely/CrossHair/blob/fe283c2890466792c9dbdf533a2a7d812fcaf399/crosshair/core.py#L173), was the root of the issue. The function was returning `True` when a SymbolicInt was being iterated over, causing the internal error to be raised. 

Not sure if patching this function is the way to go.

**Comment by pschanely** [comment]
> I am also happy to help contribute a fix here.
> 
> From my understanding of the code, the function `suspected_proxy_intolerance_exception` in file [core.py:173](https://github.com/pschanely/CrossHair/blob/fe283c2890466792c9dbdf533a2a7d812fcaf399/crosshair/core.py#L173), was the root of the issue. The function was returning `True` when a SymbolicInt was being iterated over, causing the internal error to be raised.

Your diagnostics are spot-on. This ugly bit of code was originally used to paper over parts of the standard library that we didn't support (the idea is that we should ignore paths we can't analyze, but still hope to find useful results in other paths). We now support quite a lot of the standard library, but the block is still useful for 3rd party libraries that are written in C.

> Not sure if patching this function is the way to go.

Honestly, I would like to remove`suspected_proxy_intolerance_exception` entirely at some point; I am just not sure now is the time. There are other things I'd like to investigate, involving extra concrete executions and/or getting the exception message to not leak the name of the symbolic class. Let me ponder a little bit more!

**Comment by pschanely** [comment]
Diffbehavior will find a counterexample for your code in [v0.0.79](https://crosshair.readthedocs.io/en/latest/changelog.html#version-0-0-79)!:

```
$ crosshair diffbehavior x.original x.rewrite
Given: (int_list=[0, 0, 0, 0, 0, 0, 0]),
  x.original : returns 0
   x.rewrite : raises TypeError("'SymbolicInt' object is not iterable")
```

**Comment by Abhiram98** [comment]
Great news! Thanks a lot
