### ISSUE TITLE
Implement symbolic dates and times

### ISSUE THREAD

**Issue by pschanely** [pschanely/CrossHair#4]
Per #2, all the python date/time support is in C and so we cannot analyze it effectively. Need to figure out a strategy here.

**Comment by Zac-HD** [comment]
This also came up for https://github.com/Zac-HD/stdlib-property-tests/issues/2 - there's a Python implementation of `datetime` as well as the C extension, and CPython does some import magic to access it for testing.

**Comment by pschanely** [comment]
A first cut Implementation is in! Unfortunately some kinds of datetime arithmetic is too non-linear for z3 right now, but [some things](https://github.com/pschanely/CrossHair/blob/master/crosshair/libimpl/datetimelib_test.py) work.
