### ISSUE TITLE
Consider using pydocstyle

### ISSUE THREAD

**Issue by mristin** [pschanely/CrossHair#56]
The docstrings seem to be not compliant with PEP 257. For example, the simple present tense is used instead of imperative mood. Is there a particular reason or just habit?

I am not aware of a tool that can enforce present tense, but [pydocstyle](https://pypi.org/project/pydocstyle/) can enforce imperative mood. Since the project is still young, I would suggest to introduce PEP 257 compliant docstrings as long as this requires only little effort.

**Comment by pschanely** [comment]
No particular reason! I am +1 for adding enforceable consistency.

**Comment by mristin** [comment]
Fixed by #71 .
