### ISSUE TITLE
Consider support for classes without typed attributes

### ISSUE THREAD

**Issue by pschanely** [pschanely/CrossHair#6]
Right now, CrossHair wants you to specify the attributes for your custom classes as class attributes, like so:
```
class Foo:
  age: int
  name: str
```
See also official guidance for typed class definitions [here](https://mypy.readthedocs.io/en/latest/class_basics.html#instance-and-class-attributes).

Notably, CrossHair doesn't infer types for members that are only assigned in `__init__()`. It would be nice to investigate what we could do to support this. A likely option would be to construct proxies using init's (typed) signature. (this is sub-optimal though, because we cannot represent symbolic instances that have been later in modified in ways that are not directly constructible)

**Comment by pschanely** [comment]
CrossHair now implements the likely solution provided above.

Note that such a solution still misses use cases like this, where the typed member is initially assigned to a constant or something other than an argument to `__init__`:
```
class Foo:
  def __init__(self, maxval: int):
    self.curval: int = 0
    self.maxval: int = maxval
```

In this case, CrossHair still cannot understand that `self.curval` could be something other than zero. Leaving this bug open to cover that use case.

**Comment by charles-l** [comment]
Ahhh, that makes sense. Just a suggestion, it might be worth including that class attributes must be listed outside the initializer in the README (it took me a bit of digging to find this issue). 

It looks like CrossHair doesn't call the initializer when constructing test data right now. Would it be possible to call the intializer when creating test data (so all the invarients can be specified in its definition)?

**Comment by pschanely** [comment]
(1) Yeah, I certainly agree that class authoring needs to be documented. I'll work on this - thank you!

(2) As for calling `__init__`: I think I know where you are going with this but possibly I am mis-interpreting - let me know! A bit of discussion here (this also needs to be part of the docs!):

Imagine something like a Counter() class that starts at zero and that you increment with another method - we wouldn't want CrossHair to assume that all Counter objects are always at zero. For these kinds of cases, we do not assume that objects are in a newly constructed state.

Commonly, you can instead explicitly state your invariant in your class docstring (like `inv: self.counter_number >= 0` or some such thing). If you do this, CrossHair will (1) assume that the invariant holds whenever it needs a symbolic instance of your class and (2) ensure that your `__init__` method (and every other method) maintains the invariant after executing.

**Comment by pschanely** [comment]
I've reversed some of my opinions on whether we should "just run" the constructor. The old behavior was too confusing and mysterious. CrossHair now uses the class's constructor to create instances always, and it's up to the author to ensure that valid states are constructible. This is hopefully now better documented in the ["hints for your classes"](https://crosshair.readthedocs.io/en/latest/hints_for_your_classes.html) section of the docs.
