### ISSUE TITLE
Write devdoc

### ISSUE THREAD

**Issue by mristin** [pschanely/CrossHair#60]
I see that there are no contributing guidelines yet:
> * Make a pull request. There aren't contributing guidelines yet - just check in on [gitter](https://gitter.im/Cross_Hair/Lobby) to coordinate.

 However, it would make sense to describe at least in very short lines how to run the tests, reformat the code *etc.* @pschanely could you give me at least a set of commands you execute before making a commit?

This issue is related to the issue #57.

**Comment by pschanely** [comment]
Would love it if you could help here.

I run: `pytest --doctest-modules` with the `PYTHONHASHSEED=0` environment variable.

Annoyingly, there's no way to set the hashseed on the command line. :(

**Comment by mristin** [comment]
Fixed by #71.
