### ISSUE TITLE
Move documentation to readthedocs

### ISSUE THREAD

**Issue by mristin** [pschanely/CrossHair#62]
The documentation is now a bit scattered -- what about moving it to readthedocs and using a proper Sphinx project?

I can set up a Sphinx project and create a pull request. (It makes sense to do this early in the project *before* it becomes unwieldy. Later migrations are quite painful at later stages of a project as the references need to be manually adapted.)

**Comment by pschanely** [comment]
+1
The only thing preventing me from doing this so far was unfamiliarity with Sphinx.

**Comment by mristin** [comment]
Some more points (more as notes to myself ;-)):
* Rewrite readme to use restructured text instead of markdown, 
* Include the long description in `setup.py`,
* Include twine check in pre-commit  so that we ensure that the readme will be well-displayed on pypi

**Comment by mristin** [comment]
Fixed by #79, #81 and #82.
