### ISSUE TITLE
Consider using opinionated-commit-message

### ISSUE THREAD

**Issue by mristin** [pschanely/CrossHair#63]
This is a very minor thing to consider, but helps with a clean commit history: https://github.com/mristin/opinionated-commit-message

Please let me know if I should add it to the GitHub workflows.

**Comment by pschanely** [comment]
I'll admit to feeling less strongly about this than the code formatting stuff, but it's about time for me to be making more serious commit messages anyway. Feel free!

**Comment by mristin** [comment]
It is indeed super minor! In my experience, it gives nice "safety rails" to new contributors. For example, I always look up the commit history to see what commit message format is expected. It is then pretty confusing if the tenses are mixed, and I wonder which tense is expected.

**Comment by mristin** [comment]
@pschanely could you please re-review? I added a section to the contributing guidelines and included the link in the error message.

I set up the action so that both the commit messages and pull requests must always contain both a subject (*i.e.* a header or title) and a body. This forced me in practice to write much more informative commit messages. 

Most of the times, the developer is at least forced to reference an issue that the commit fixes. Other times, the developer has to write what the problem was (*why*). This really helps when you need to backtrack. However, I am not so sure if it makes sense to document the history of the code *at this point* while it is all pretty much in flux. 

(I personally think it does pays off given how little effort it takes to write an additional sentence or two in comparison to work that almost all pull requests involve. On the other hand, I also see the other perspective that writing more elaborate commit messages can hinder the creativity and become a barrier to quick changes.)

**Comment by pschanely** [comment]
I am willing to give this a try! I am doing a lot of untracked work right now, but I expect that to die down over time. I also occasionally have a "remove unused import" commit message that I might struggle to describe, but the benefits probably outweigh a few awkward cases.

**Comment by mristin** [comment]
> I also occasionally have a "remove unused import" commit message that I might struggle to describe,  ...

What worked for me in those cases is just to write down in the body that this is a purely cosmetic/formatting commit (which is useful information in its own right). For example, another developer might wonder whether there was something *procedural* involved in the import as the code would be executed during the import *etc.*
