### ISSUE TITLE
Document `check` and `watch` commands at line number

### ISSUE THREAD

**Issue by mristin** [pschanely/CrossHair#91]
Hi @pschanely ,
I realized while reading the docs for [crosshair-vscode] that the feature for checking and watching a module at the function under the particular line has not been documented in the help message (see [the documentation of the command-line interface]? Is that intended?

The help says only:
```
positional arguments:
  FILE                  file/directory or fully qualified module, class, or function
```

Perhaps you want to include examples in the help as well?

[crosshair-vscode]: https://github.com/mristin/crosshair-vscode/
[the documentation of the command-line interface]: https://crosshair.readthedocs.io/en/latest/command-line_interface.html

**Comment by pschanely** [comment]
Ah; not intentional.

I started to try and talk about this more in the [what code is analyzed](https://crosshair.readthedocs.io/en/latest/what_code_is_analyzed.html) section. It felt like this was a lot to talk about in a help message. OTOH, we probably could expand it to a multiline message. WDYT?

**Comment by mristin** [comment]
I would indeed prefer a more detailed help message in this case as it was not immediately clear that you can specify a line number and also how to concatenate it.

**Comment by mristin** [comment]
P.S. maybe also rename FILE into TARGET?

**Comment by pschanely** [comment]
Added!
